
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.TenantScalarFieldEnum = {
  id: 'id',
  business_name: 'business_name',
  slug: 'slug',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  plan: 'plan',
  status: 'status',
  trial_ends_at: 'trial_ends_at',
  current_period_start: 'current_period_start',
  current_period_end: 'current_period_end',
  stripe_customer_id: 'stripe_customer_id',
  stripe_subscription_id: 'stripe_subscription_id',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  address: 'address',
  phone: 'phone',
  vat_number: 'vat_number',
  vat_rate: 'vat_rate',
  timezone: 'timezone',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  username: 'username',
  password: 'password',
  role: 'role',
  is_active: 'is_active',
  branch_id: 'branch_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  token_hash: 'token_hash',
  expires_at: 'expires_at',
  created_at: 'created_at'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name_en: 'name_en',
  name_ar: 'name_ar'
};

exports.Prisma.ManufacturerScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  country: 'country'
};

exports.Prisma.DrugScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name_en: 'name_en',
  name_ar: 'name_ar',
  barcode: 'barcode',
  generic_name: 'generic_name',
  category_id: 'category_id',
  manufacturer_id: 'manufacturer_id',
  unit: 'unit',
  cost_price: 'cost_price',
  sell_price: 'sell_price',
  vat_included: 'vat_included',
  requires_prescription: 'requires_prescription',
  description: 'description',
  image_url: 'image_url',
  is_active: 'is_active',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_by: 'updated_by',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.DrugSubstituteScalarFieldEnum = {
  drug_id: 'drug_id',
  substitute_id: 'substitute_id'
};

exports.Prisma.InventoryScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  drug_id: 'drug_id',
  branch_id: 'branch_id',
  quantity: 'quantity',
  reorder_point: 'reorder_point',
  shelf_location: 'shelf_location',
  updated_at: 'updated_at'
};

exports.Prisma.InventoryBatchScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  inventory_id: 'inventory_id',
  batch_no: 'batch_no',
  quantity: 'quantity',
  cost_price: 'cost_price',
  expiry_date: 'expiry_date',
  received_at: 'received_at'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  drug_id: 'drug_id',
  branch_id: 'branch_id',
  movement_type: 'movement_type',
  quantity: 'quantity',
  quantity_before: 'quantity_before',
  quantity_after: 'quantity_after',
  reference_id: 'reference_id',
  reference_type: 'reference_type',
  notes: 'notes',
  created_by: 'created_by',
  created_at: 'created_at'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  name: 'name',
  contact_person: 'contact_person',
  phone: 'phone',
  email: 'email',
  address: 'address',
  payment_terms_days: 'payment_terms_days',
  is_active: 'is_active',
  created_at: 'created_at',
  updated_at: 'updated_at',
  deleted_at: 'deleted_at'
};

exports.Prisma.PurchaseOrderScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  supplier_id: 'supplier_id',
  branch_id: 'branch_id',
  status: 'status',
  expected_delivery_date: 'expected_delivery_date',
  notes: 'notes',
  total_amount: 'total_amount',
  created_by: 'created_by',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.PurchaseOrderItemScalarFieldEnum = {
  id: 'id',
  purchase_order_id: 'purchase_order_id',
  drug_id: 'drug_id',
  quantity_ordered: 'quantity_ordered',
  agreed_cost_price: 'agreed_cost_price',
  quantity_received: 'quantity_received'
};

exports.Prisma.GRNScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  supplier_id: 'supplier_id',
  purchase_order_id: 'purchase_order_id',
  branch_id: 'branch_id',
  invoice_number: 'invoice_number',
  invoice_date: 'invoice_date',
  total_cost: 'total_cost',
  is_paid: 'is_paid',
  payment_date: 'payment_date',
  created_by: 'created_by',
  created_at: 'created_at'
};

exports.Prisma.GRNItemScalarFieldEnum = {
  id: 'id',
  grn_id: 'grn_id',
  drug_id: 'drug_id',
  batch_no: 'batch_no',
  quantity: 'quantity',
  cost_price: 'cost_price',
  expiry_date: 'expiry_date'
};

exports.Prisma.CashierSessionScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  cashier_id: 'cashier_id',
  branch_id: 'branch_id',
  status: 'status',
  opening_float: 'opening_float',
  closing_float: 'closing_float',
  total_sales: 'total_sales',
  total_returns: 'total_returns',
  opened_at: 'opened_at',
  closed_at: 'closed_at',
  notes: 'notes'
};

exports.Prisma.CartScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  session_id: 'session_id',
  status: 'status',
  customer_name: 'customer_name',
  discount_type: 'discount_type',
  discount_value: 'discount_value',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.CartItemScalarFieldEnum = {
  id: 'id',
  cart_id: 'cart_id',
  drug_id: 'drug_id',
  quantity: 'quantity',
  unit_price: 'unit_price',
  discount_percent: 'discount_percent'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  tenant_id: 'tenant_id',
  receipt_number: 'receipt_number',
  session_id: 'session_id',
  cashier_id: 'cashier_id',
  branch_id: 'branch_id',
  cart_id: 'cart_id',
  type: 'type',
  customer_name: 'customer_name',
  subtotal: 'subtotal',
  discount_total: 'discount_total',
  vat_total: 'vat_total',
  grand_total: 'grand_total',
  notes: 'notes',
  original_transaction_id: 'original_transaction_id',
  created_at: 'created_at'
};

exports.Prisma.TransactionItemScalarFieldEnum = {
  id: 'id',
  transaction_id: 'transaction_id',
  drug_id: 'drug_id',
  quantity: 'quantity',
  unit_price: 'unit_price',
  cost_price: 'cost_price',
  discount_percent: 'discount_percent',
  discount_amount: 'discount_amount',
  vat_rate: 'vat_rate',
  vat_amount: 'vat_amount',
  line_total: 'line_total'
};

exports.Prisma.TransactionPaymentScalarFieldEnum = {
  id: 'id',
  transaction_id: 'transaction_id',
  method: 'method',
  amount: 'amount'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.SubscriptionPlan = exports.$Enums.SubscriptionPlan = {
  STARTER: 'STARTER',
  PRO: 'PRO',
  ENTERPRISE: 'ENTERPRISE'
};

exports.SubscriptionStatus = exports.$Enums.SubscriptionStatus = {
  TRIAL: 'TRIAL',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  CANCELLED: 'CANCELLED'
};

exports.UserRole = exports.$Enums.UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_OWNER: 'TENANT_OWNER',
  ADMIN: 'ADMIN',
  PHARMACIST: 'PHARMACIST',
  CASHIER: 'CASHIER',
  VIEWER: 'VIEWER'
};

exports.DrugUnit = exports.$Enums.DrugUnit = {
  TABLET: 'TABLET',
  CAPSULE: 'CAPSULE',
  BOTTLE: 'BOTTLE',
  BOX: 'BOX',
  AMPOULE: 'AMPOULE',
  SACHET: 'SACHET',
  TUBE: 'TUBE',
  VIAL: 'VIAL'
};

exports.StockMovementType = exports.$Enums.StockMovementType = {
  PURCHASE_RECEIVED: 'PURCHASE_RECEIVED',
  SALE: 'SALE',
  RETURN_FROM_CUSTOMER: 'RETURN_FROM_CUSTOMER',
  RETURN_TO_SUPPLIER: 'RETURN_TO_SUPPLIER',
  ADJUSTMENT_INCREASE: 'ADJUSTMENT_INCREASE',
  ADJUSTMENT_DECREASE: 'ADJUSTMENT_DECREASE',
  PHYSICAL_COUNT_CORRECTION: 'PHYSICAL_COUNT_CORRECTION',
  EXPIRY_WRITEOFF: 'EXPIRY_WRITEOFF'
};

exports.PurchaseOrderStatus = exports.$Enums.PurchaseOrderStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  FULLY_RECEIVED: 'FULLY_RECEIVED',
  CANCELLED: 'CANCELLED'
};

exports.SessionStatus = exports.$Enums.SessionStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
};

exports.CartStatus = exports.$Enums.CartStatus = {
  ACTIVE: 'ACTIVE',
  HELD: 'HELD',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  SALE: 'SALE',
  RETURN: 'RETURN'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  CARD: 'CARD',
  INSURANCE: 'INSURANCE',
  STORE_CREDIT: 'STORE_CREDIT'
};

exports.Prisma.ModelName = {
  Tenant: 'Tenant',
  Subscription: 'Subscription',
  Branch: 'Branch',
  User: 'User',
  RefreshToken: 'RefreshToken',
  Category: 'Category',
  Manufacturer: 'Manufacturer',
  Drug: 'Drug',
  DrugSubstitute: 'DrugSubstitute',
  Inventory: 'Inventory',
  InventoryBatch: 'InventoryBatch',
  StockMovement: 'StockMovement',
  Supplier: 'Supplier',
  PurchaseOrder: 'PurchaseOrder',
  PurchaseOrderItem: 'PurchaseOrderItem',
  GRN: 'GRN',
  GRNItem: 'GRNItem',
  CashierSession: 'CashierSession',
  Cart: 'Cart',
  CartItem: 'CartItem',
  Transaction: 'Transaction',
  TransactionItem: 'TransactionItem',
  TransactionPayment: 'TransactionPayment'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
